services:
  postgresdb:
    image: postgres:16-alpine
    container_name: inventory_postgres
    # 👇 1. DI SINI KITA PASANG ENV_FILE-NYA
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - inventory_network

  backend:
    build: .
    container_name: inventory_backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - PORT=8080
      - DB_HOST=postgresdb
      - DB_PORT=5432
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    depends_on:
      postgresdb:
        condition: service_healthy
    networks:
      - inventory_network

volumes:
  postgres_data:

networks:
  inventory_network:
    driver: bridge
